### ISSUE TITLE
gitkraken-cli is dected as OSX/DDoS.DDosia.ext virus by Intego VirusBarrier

### ISSUE THREAD

**Issue by roman-suvorov-onseo** [gitkraken/gk-cli#6] opened 2023-06-06 06:59 UTC
![gkcli](https://github.com/gitkraken/gk-cli/assets/129750128/68193ce5-facb-4192-b06f-7ced73ce90c2)

**Comment by sergiolms** [comment] 2023-06-06 09:40
Hi @roman-suvorov-onseo welcome and thank you for submitting feedback!

We've reported this to Intego to provide us more information to tackle the problem and take actions to correct this false positive.

In the meantime, you can trust the `gk` process in the Quarantine list. To move quarantined files into Trusted Items at once:
- Open VirusBarrier application.
- Click on "Quarantine" tab.
- Select the `gk` file.
- Click on "Trust" button.
- Select "Trusted Items": previous quarantined file is in this list now.
- Quit VirusBarrier.

**Comment by sergiolms** [comment] 2023-06-06 14:38
@roman-suvorov-onseo I got this response from Intego VirusBarrier team:

> According to our Malware Team, a fix has been added to 2023060601 virus definitions, published today.
Intel's x86_64 gk process should no longer be seen as a false positive.

Please check again or update VirusBarrier and let us know if the problem persists.

**Comment by thenexxuz** [comment] 2023-06-07 19:47
@sergiolms not sure if your previous message was meant for this issue.

**Comment by sergiolms** [comment] 2023-06-12 10:11
I ran [`Intego VirusBarrier Scanner`](https://apps.apple.com/es/app/intego-virusbarrier-scanner/id1200445649?mt=12) and I couldn't reproduce this anymore, so I'm closing this issue. Thanks for reporting it!

**Closed by sergiolms** 2023-06-12 10:11 UTC
Labels: status: needs information, type: bug
